spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  main:
    allow-circular-references: true
jwt:
  secret: secret